language: node_js
node_js:
- 0.8
notifications:
  irc: irc.freenode.org#generator-travis-ci
branches:
  only:
  - master
env:
  global:
  - GH_OWNER: mysterycommand
  - GH_PROJECT_NAME: panaraimport.com
  - secure: ZpsaVwSjCAh6I9c/zHSZoa4xzPrIGfK4GolTZjFweaMAN22kgH6sQa+/BjNZT6Z5cUWnDjqvQSf+IdmCLW92P6r+wUWv7Eov/xJC2M0iymlDqg6GeExPsKnTCjuKsxSjyNdViJtOga8YlG16gXZv9MCocLjn1/wN+Fzpd+EHjzI=
before_script:
- gem update --system
- gem install compass
- npm install -g grunt-cli bower
script:
- bower install
- grunt
after_success:
- git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
- cd site
- if git checkout gh-pages; then git checkout -b gh-pages; fi
- git rm -r .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -f .
- git config user.email "matt@mysterycommand.com"
- git config user.name "Matt Hayes"
- git commit -am "GitHub Pages commit. [ci skip]"
- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
