language: node_js
node_js:
    - stable
branches:
    only:
    - master
script:
    - npm test
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: Rzx4iSzpFQGhboJzKQ6DiF+IPYSc0CeJyKiWTcr8ZWDRiCZxbnnfxC1v5+OT5XUV/7gziw1+6UHaHSQaGyJNm8x/PeFafg2LXb30uW+PcIPVg7QLjfcTojJMizAUecAvQHaGomCLvKWJnelWZIw7myefMDhSCuqKgrfcogIJKa4=
after_success:
    - npm run deploy
