language: node_js
node_js:
    - stable
branches:
    only:
    - master
script:
    - npm test
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: eGzaEhfzlSKFqfHGrM6EXvuSNlKpWuTow37xF7NxQRzz/PYYhyAtWtZyxAPSgJNcqLc2XxSVwLOd6f2xycq5ztyVzDNEtjIOxdVaXM5nxinsKp+oqMCFgGfiEdKeNjPviSGbW8YJmzX70d7x/Xf67JnZmqxvADTIzUTj7LXSRRE=
after_success:
    - npm run deploy
